module OAuth
  module TTY
    class Command
      include Auth::Sanitizer::FilteredAttributes

      def initialize: (untyped stdout, untyped stdin, untyped stderr, untyped arguments) -> void
      def run: () -> untyped
      def required_options: () -> Array[untyped]

      private

      attr_reader options: untyped
    end
  end
end
